# Numpy

### 1. ndarray(Numpy Dimensional Array)

In [18]:
import numpy as np

In [19]:
a = np.array([1,4,5,8], float)
print(a)

[1. 4. 5. 8.]


In [20]:
a[3],a.dtype, a.shape

(8.0, dtype('float64'), (4,))

### 2. Array shape

In [21]:
# 1차원 - vector
a = np.array([1,4,5,8],float)

In [22]:
# 2차원 - matrix
m =[[1,4],[5,8]]
b = np.array(m, float)
print(b)

[[1. 4.]
 [5. 8.]]


In [23]:
# 3차원 - tensor
t = [[[1,4],[5,8]],[[11,14],[15,18]]]
c= np.array(t,float)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]])

In [24]:
a.shape,  b.shape,   c.shape
# 1차원      2차원       3차원

((4,), (2, 2), (2, 2, 2))

In [25]:
# ndim
a.ndim, b.ndim, c.ndim

(1, 2, 3)

In [26]:
#size : element의 개수가 몇 개인지
a.size, b.size, c.size

(4, 4, 8)

In [27]:
c = np.array(t, dtype = np, float32)

SyntaxError: positional argument follows keyword argument (<ipython-input-27-f544d65dde94>, line 1)

### - reshape: size는 동일(element개수 동일) 

In [14]:
c.reshape(2,4).shape

(2, 4)

In [15]:
c.reshape(2,4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]])

In [16]:
c.reshape(8,)

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.])

In [17]:
# -1은 한번만 사용 가능
c.reshape(-1,4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]])

In [32]:
# flatten - 1차원으로 변환
c.flatten()

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.])

### 3.indexing and slicing

In [34]:
a = np.arange(6)        #a = np.array(range(6))랑 같음
a

array([0, 1, 2, 3, 4, 5])

In [36]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [37]:
a[0][1] #리스트

1

In [39]:
a[0][1], a[0,1] #numpy에서는 꺽쇠 한번이면 된다 a[0,1]

(1, 1)

In [40]:
# 리스트와는 달리 numpy는 2차원도(행, 열 모두에 대해) slicing가능
a[:,:2]

array([[0, 1],
       [3, 4]])

In [46]:
b = np.arange(16).reshape(-1,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
b[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [49]:
# 0,1,4,5,8,9
b[:3,:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [50]:
# 세번째 열까지는 x, 마지막 열은 Y
X, Y = b[:,:-1], b[:,-1]     #맨 마지막을 -1로 표현
X.shape, Y.shape

((4, 3), (4,))

### 4. creation

In [51]:
np.arange(1,10)
#np,arange(10)이랑 같음

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(0,1.1, 0.1)   # 실수를 소숫점으로

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [53]:
np.arange(0,1.1, 0.1).tolist()

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0]

In [54]:
np.arange(0,1.1, 0.1).tolist()[3]==0.3

False

In [ ]:
# 실수는 우리가 원하는 값을 정확하게 표시하지 못한다
# np.abs(np.arange(0,1.1, 0.1).tolist()[(3)-0.3]

In [57]:
#ones, zeros, empty
a = np.zeros((5,),dtype=np.int8)
a

array([0, 0, 0, 0, 0], dtype=int8)

In [58]:
b = np.ones((2,4),dtype=np.int8)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [59]:
np.empty((2,5))
#empty는 할당만, zeros는 할당하고 초기화

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ]])

In [61]:
a = np.arange(24).reshape(4,-1)
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [63]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [64]:
# 단위행렬: identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# eye - 대각선이 1인 행렬
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [29]:
np.eye(3,5,2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### -random sampling

In [31]:
np.random.seed(2021)
#균등분포
np.random.uniform(0,1,10).reshape(2,5)

array([[0.60597828, 0.73336936, 0.13894716, 0.31267308, 0.99724328],
       [0.12816238, 0.17899311, 0.75292543, 0.66216051, 0.78431013]])

In [33]:
np.random.normal(0,1,10).reshape(2,5)   #(표준정규분포:normal)

array([[-1.33620597,  0.30372151, -0.72015884,  2.5449146 ,  1.31729112],
       [ 0.0726303 , -0.25610814,  0.13801041,  1.14723599,  1.37626076]])

In [35]:
#이항분포, 포아송(poission), t-분포(standard_t), f-분포(f)
np.random.binomial(100,1/6,10) 

array([20, 14, 18, 18, 15, 21, 17, 25, 16, 12])