In [3]:
import numpy as np

In [4]:
#1
a = np.array([10,20,30,40,50,60,70,80]).reshape(2,4)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [5]:
#2
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
#2-1
m[1,2]

7

In [7]:
#2-2
m[2,4]

14

In [8]:
#2-3
m[1:2,1:3]

array([[6, 7]])

In [9]:
#2-4
m[1:3,2:3]


array([[ 7],
       [12]])

In [10]:
m[1:,2]

array([ 7, 12])

In [126]:
#2-5
[m[0:1,3:5],m[1:2,3:5]]

[array([[3, 4]]), array([[8, 9]])]

In [129]:
# 3
f = m.flatten()

In [147]:
f%3==0

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False])

In [148]:
#3-1
f[f%3==0]

array([ 0,  3,  6,  9, 12])

In [150]:
f%4==1

array([False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False])

In [151]:
#3-2
f[f%4==1]

array([ 1,  5,  9, 13])

In [157]:
#3-3
f%3==0, f%4==1

(array([ True, False, False,  True, False, False,  True, False, False,
         True, False, False,  True, False, False]),
 array([False,  True, False, False, False,  True, False, False, False,
         True, False, False, False,  True, False]))

In [ ]:
f[np.logical_and]

In [163]:
#4
np.eye(5,5, k=-1)*3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [171]:
#5
c = np.random.randint(0,10,size =(5,6))
c

array([[9, 1, 5, 8, 3, 2],
       [5, 5, 9, 6, 4, 3],
       [7, 4, 2, 8, 3, 8],
       [7, 6, 1, 9, 5, 1],
       [0, 4, 2, 3, 4, 1]])

In [175]:
#5-1
np.max(c)

9

In [176]:
#5-2
c.sum(axis=1)

array([28, 32, 32, 29, 14])

In [177]:
#5-3
c.max(axis=1)

array([9, 9, 8, 9, 4])

In [178]:
#5-4
c.mean(axis=0)

array([5.6, 4. , 3.8, 6.8, 3.8, 3. ])

In [179]:
#5-5
c.min(axis=0)

array([0, 1, 1, 3, 3, 1])

In [187]:
#6
d = np.array([1,2,3,4,46,99,100,71,81,59,90,100]).reshape(3,4)
d

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [193]:
num = np.array([1,2,3,4]).reshape(1,4)
eng = np.array([46,99,100,71]).reshape(1,4)
mat = np.array([81,59,90,100]).reshape(1,4)
d = np.vstack((num,eng,mat))
d

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [206]:
#6
d1 = d[:,d[1].argsort()]
d1

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [18]:
#내림차순
d1 = d[:,np.argsort(d[1])[::-1]]
d1

NameError: name 'd' is not defined

In [23]:
#7
#import random
#for i in range(100):
#    e = np.random.randint(1,7)

In [20]:
np.random.seed(2021)
dice = np.random.randint(1,7,100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [24]:
np.mean(dice)

3.7

In [25]:
#8
np.random.seed(2021)
price = 10000
rate = np.random.normal(0,1,10)
for i in range(10):
    price += np.round(price * rate[i] * 0.01)
    print(price, end = ", ")

10149.0, 10218.0, 10175.0, 10093.0, 10149.0, 10077.0, 10191.0, 10257.0, 10268.0, 10311.0, 

In [29]:
#8
np.random.seed(2021)
price_list = []
rate = np.random.normal(0,1,250)
price = 10000
for i in range(250):
    price += np.round(price * rate[i] * 0.01)
    price_list.append(price)
price_array = np.array(price_list, int)

In [31]:
print(price_array[:10])
print(price_array[:-10])

[10149 10218 10175 10093 10149 10077 10191 10257 10268 10311]
[10149 10218 10175 10093 10149 10077 10191 10257 10268 10311 10324 10237
 10279 10290 10094 10205 10062 10039  9905  9935  9863 10114 10247 10254
 10228 10242 10359 10502 10452 10507 10663 10821 10900 10858 10888 10894
 10780 10763 10462 10500 10525 10575 10597 10694 10543 10672 10614 10710
 10605 10538 10625 10489 10453 10340 10441 10484 10470 10400 10527 10429
 10578 10565 10640 10717 10732 10662 10590 10682 10789 10749 10870 10956
 10764 10677 10526 10441 10524 10709 10701 10746 10763 10757 10699 10795
 10819 10957 11026 11066 11469 11331 11180 11321 11248 11501 11385 11371
 11322 11370 11456 11342 11258 11310 11452 11401 11463 11528 11478 11566
 11622 11520 11441 11493 11410 11246 11488 11494 11568 11444 11472 11515
 11563 11701 11828 11861 11971 12011 12226 12110 12041 12071 12133 12080
 12296 12318 12365 12429 12503 12741 12817 12801 12820 12892 12815 12864
 12784 12804 12623 12865 12996 12966 13026 13063 12909 13106 1